[2024-12-17T12:22:52.275] [ERROR] error - ReferenceError: aaaaa is not defined
    at login (C:\reactProject\AIGC-node\controller\user.js:5:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async errorhandler (C:\reactProject\AIGC-node\config\errorhandler.js:5:5)
    at async responseHandler (C:\reactProject\AIGC-node\config\result.js:18:3)
    at async cors (C:\reactProject\AIGC-node\node_modules\@koa\cors\index.js:109:16)
    at async bodyParser (C:\reactProject\AIGC-node\node_modules\koa-bodyparser\index.js:78:5)
[2024-12-17T13:30:03.634] [ERROR] error - ReferenceError: name is not defined
    at login (C:\reactProject\AIGC-node\controller\user.js:5:31)
    at dispatch (C:\reactProject\AIGC-node\node_modules\koa-compose\index.js:42:32)
    at C:\reactProject\AIGC-node\node_modules\@koa\router\lib\router.js:261:18
    at dispatch (C:\reactProject\AIGC-node\node_modules\koa-compose\index.js:42:32)
    at C:\reactProject\AIGC-node\node_modules\koa-compose\index.js:34:12
    at dispatch (C:\reactProject\AIGC-node\node_modules\@koa\router\lib\router.js:266:33)
    at dispatch (C:\reactProject\AIGC-node\node_modules\koa-compose\index.js:42:32)
    at errorhandler (C:\reactProject\AIGC-node\config\errorhandler.js:5:11)
    at dispatch (C:\reactProject\AIGC-node\node_modules\koa-compose\index.js:42:32)
    at responseHandler (C:\reactProject\AIGC-node\config\result.js:18:9)
[2024-12-17T13:30:53.649] [ERROR] error - { msg: '用户名不能为空', code: 422 }
[2024-12-17T13:31:45.366] [ERROR] error - { msg: '用户名不能为空', code: 422 }
[2024-12-17T13:33:11.862] [ERROR] error - { msg: '缺少name字段', code: 400 }
[2024-12-17T13:34:02.656] [ERROR] error - { msg: '缺少name字段', code: 400 }
[2024-12-17T13:37:13.806] [ERROR] error - { msg: '年龄不能为空', code: 422 }
[2024-12-17T23:15:12.324] [ERROR] error - Error
    at Query.run (C:\reactProject\AIGC-node\node_modules\sequelize\lib\dialects\mysql\query.js:52:25)
    at C:\reactProject\AIGC-node\node_modules\sequelize\lib\sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.insert (C:\reactProject\AIGC-node\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)
    at async model.save (C:\reactProject\AIGC-node\node_modules\sequelize\lib\model.js:2490:35)
    at async user-info.create (C:\reactProject\AIGC-node\node_modules\sequelize\lib\model.js:1362:12)
    at async login (C:\reactProject\AIGC-node\controller\user.js:10:5)
    at async errorhandler (C:\reactProject\AIGC-node\config\errorhandler.js:5:5)
    at async responseHandler (C:\reactProject\AIGC-node\config\result.js:18:3)
    at async cors (C:\reactProject\AIGC-node\node_modules\@koa\cors\index.js:109:16) {
  name: 'SequelizeUniqueConstraintError',
  errors: [
    ValidationErrorItem {
      message: 'PRIMARY must be unique',
      type: 'unique violation',
      path: 'PRIMARY',
      value: '15835535784',
      origin: 'DB',
      instance: [user-info],
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    }
  ],
  parent: Error: Duplicate entry '15835535784' for key 'user-info.PRIMARY'
      at Packet.asError (C:\reactProject\AIGC-node\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Execute.execute (C:\reactProject\AIGC-node\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (C:\reactProject\AIGC-node\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_DUP_ENTRY',
    errno: 1062,
    sqlState: '23000',
    sqlMessage: "Duplicate entry '15835535784' for key 'user-info.PRIMARY'",
    sql: 'INSERT INTO `user-info` (`phone`,`createdAt`,`updatedAt`) VALUES (?,?,?);',
    parameters: [ '15835535784', '2024-12-17 15:15:12', '2024-12-17 15:15:12' ]
  },
  original: Error: Duplicate entry '15835535784' for key 'user-info.PRIMARY'
      at Packet.asError (C:\reactProject\AIGC-node\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Execute.execute (C:\reactProject\AIGC-node\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (C:\reactProject\AIGC-node\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_DUP_ENTRY',
    errno: 1062,
    sqlState: '23000',
    sqlMessage: "Duplicate entry '15835535784' for key 'user-info.PRIMARY'",
    sql: 'INSERT INTO `user-info` (`phone`,`createdAt`,`updatedAt`) VALUES (?,?,?);',
    parameters: [ '15835535784', '2024-12-17 15:15:12', '2024-12-17 15:15:12' ]
  },
  fields: { PRIMARY: '15835535784' },
  sql: 'INSERT INTO `user-info` (`phone`,`createdAt`,`updatedAt`) VALUES (?,?,?);'
}
[2024-12-17T23:19:17.337] [ERROR] error - Error
    at Query.run (C:\reactProject\AIGC-node\node_modules\sequelize\lib\dialects\mysql\query.js:52:25)
    at C:\reactProject\AIGC-node\node_modules\sequelize\lib\sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.insert (C:\reactProject\AIGC-node\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)
    at async model.save (C:\reactProject\AIGC-node\node_modules\sequelize\lib\model.js:2490:35)
    at async user-info.create (C:\reactProject\AIGC-node\node_modules\sequelize\lib\model.js:1362:12)
    at async login (C:\reactProject\AIGC-node\controller\user.js:10:5)
    at async errorhandler (C:\reactProject\AIGC-node\config\errorhandler.js:5:5)
    at async responseHandler (C:\reactProject\AIGC-node\config\result.js:18:3)
    at async cors (C:\reactProject\AIGC-node\node_modules\@koa\cors\index.js:109:16) {
  name: 'SequelizeDatabaseError',
  parent: Error: Field 'createdAt' doesn't have a default value
      at Packet.asError (C:\reactProject\AIGC-node\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Execute.execute (C:\reactProject\AIGC-node\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (C:\reactProject\AIGC-node\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_NO_DEFAULT_FOR_FIELD',
    errno: 1364,
    sqlState: 'HY000',
    sqlMessage: "Field 'createdAt' doesn't have a default value",
    sql: 'INSERT INTO `user-info` (`phone`) VALUES (?);',
    parameters: [ '17727127502' ]
  },
  original: Error: Field 'createdAt' doesn't have a default value
      at Packet.asError (C:\reactProject\AIGC-node\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Execute.execute (C:\reactProject\AIGC-node\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (C:\reactProject\AIGC-node\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_NO_DEFAULT_FOR_FIELD',
    errno: 1364,
    sqlState: 'HY000',
    sqlMessage: "Field 'createdAt' doesn't have a default value",
    sql: 'INSERT INTO `user-info` (`phone`) VALUES (?);',
    parameters: [ '17727127502' ]
  },
  sql: 'INSERT INTO `user-info` (`phone`) VALUES (?);',
  parameters: [ '17727127502' ]
}
[2024-12-17T23:20:28.639] [ERROR] error - Error
    at Query.run (C:\reactProject\AIGC-node\node_modules\sequelize\lib\dialects\mysql\query.js:52:25)
    at C:\reactProject\AIGC-node\node_modules\sequelize\lib\sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.insert (C:\reactProject\AIGC-node\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)
    at async model.save (C:\reactProject\AIGC-node\node_modules\sequelize\lib\model.js:2490:35)
    at async user-info.create (C:\reactProject\AIGC-node\node_modules\sequelize\lib\model.js:1362:12)
    at async login (C:\reactProject\AIGC-node\controller\user.js:10:5)
    at async errorhandler (C:\reactProject\AIGC-node\config\errorhandler.js:5:5)
    at async responseHandler (C:\reactProject\AIGC-node\config\result.js:18:3)
    at async cors (C:\reactProject\AIGC-node\node_modules\@koa\cors\index.js:109:16) {
  name: 'SequelizeDatabaseError',
  parent: Error: Field 'createdAt' doesn't have a default value
      at Packet.asError (C:\reactProject\AIGC-node\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Execute.execute (C:\reactProject\AIGC-node\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (C:\reactProject\AIGC-node\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_NO_DEFAULT_FOR_FIELD',
    errno: 1364,
    sqlState: 'HY000',
    sqlMessage: "Field 'createdAt' doesn't have a default value",
    sql: 'INSERT INTO `user-info` (`phone`) VALUES (?);',
    parameters: [ '17727127502' ]
  },
  original: Error: Field 'createdAt' doesn't have a default value
      at Packet.asError (C:\reactProject\AIGC-node\node_modules\mysql2\lib\packets\packet.js:740:17)
      at Execute.execute (C:\reactProject\AIGC-node\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:475:34)
      at PacketParser.onPacket (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:93:12)
      at PacketParser.executeStart (C:\reactProject\AIGC-node\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\reactProject\AIGC-node\node_modules\mysql2\lib\base\connection.js:100:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_NO_DEFAULT_FOR_FIELD',
    errno: 1364,
    sqlState: 'HY000',
    sqlMessage: "Field 'createdAt' doesn't have a default value",
    sql: 'INSERT INTO `user-info` (`phone`) VALUES (?);',
    parameters: [ '17727127502' ]
  },
  sql: 'INSERT INTO `user-info` (`phone`) VALUES (?);',
  parameters: [ '17727127502' ]
}
